# Generated by Django 4.2.16 on 2024-10-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=30, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Имя')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('user_date_add', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='Название')),
                ('recipe_description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('stages_preparation', models.TextField(verbose_name='Этапы приготовления')),
                ('time_preparation', models.IntegerField(verbose_name='Время приготовления, мин.')),
                ('food_image', models.ImageField(blank=True, upload_to='food_images', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
